import { NextRequest, NextResponse } from "next/server";
import { exec } from "child_process";
import fs from "fs";
import fsPromises from "fs/promises";
import path from "path";
import os from "os";
import { promisify } from "util";
import { acquireCompileLock, releaseCompileLock } from "@/lib/redis";

const execPromise = promisify(exec);

function getPdfLatexPath(): string {
  const customPath = "/Library/TeX/texbin/pdflatex";
  return fs.existsSync(customPath) ? customPath : "pdflatex";
}

export async function POST(req: NextRequest) {
  let jobId: string | null = null;
  let lockAcquired = false;
  const uniqueId = Math.random().toString(36).substring(7);
  const tmpDir = os.tmpdir();

  const texFilePath = path.join(tmpDir, `resume_${uniqueId}.tex`);
  const pdfFilePath = path.join(tmpDir, `resume_${uniqueId}.pdf`);
  const auxFilePath = path.join(tmpDir, `resume_${uniqueId}.aux`);
  const logFilePath = path.join(tmpDir, `resume_${uniqueId}.log`);
  const outFilePath = path.join(tmpDir, `resume_${uniqueId}.out`);

  try {
    const body = await req.json();
    const { latex, jobId: incomingJobId } = body as {
      latex?: string;
      jobId?: string;
    };
    jobId = incomingJobId ?? null;

    if (!latex) {
      return NextResponse.json({ error: "Missing latex code payload" }, { status: 400 });
    }

    if (jobId) {
      const success = await acquireCompileLock(jobId);
      if (!success) {
        console.warn(
          `[api-compiler] Compilation request blocked: lock already active for job ${jobId}.`
        );
        return NextResponse.json(
          { error: "A compilation is already in progress for this resume." },
          { status: 423 }
        );
      }
      lockAcquired = true;
    }

    await fsPromises.writeFile(texFilePath, latex, "utf-8");

    const pdflatexPath = getPdfLatexPath();
    const compileCmd = `"${pdflatexPath}" -interaction=nonstopmode -output-directory="${tmpDir}" "${texFilePath}"`;

    try {
      await execPromise(compileCmd);
    } catch (execErr: unknown) {
      const err = execErr as { stdout?: string; message?: string };
      console.error(
        "[api-compiler] pdflatex execution crash:",
        err.stdout || err.message
      );
      return NextResponse.json(
        {
          error: "pdflatex compilation failed",
          details: err.stdout || err.message,
        },
        { status: 500 }
      );
    }

    if (!fs.existsSync(pdfFilePath)) {
      let logContent = "";
      try {
        logContent = await fsPromises.readFile(logFilePath, "utf-8");
      } catch {
        // ignore missing log
      }
      return NextResponse.json(
        {
          error: "PDF was not successfully generated by compiler",
          logs: logContent.substring(Math.max(0, logContent.length - 2000)),
        },
        { status: 500 }
      );
    }

    const pdfBuffer = await fsPromises.readFile(pdfFilePath);

    return new NextResponse(pdfBuffer, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="resume_${uniqueId}.pdf"`,
      },
    });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Internal Server Error";
    console.error("[api-compiler] Local compilation API failed:", err);
    return NextResponse.json({ error: message }, { status: 500 });
  } finally {
    await Promise.all([
      fsPromises.unlink(texFilePath).catch(() => {}),
      fsPromises.unlink(pdfFilePath).catch(() => {}),
      fsPromises.unlink(auxFilePath).catch(() => {}),
      fsPromises.unlink(logFilePath).catch(() => {}),
      fsPromises.unlink(outFilePath).catch(() => {}),
    ]);

    if (jobId && lockAcquired) {
      await releaseCompileLock(jobId);
    }
  }
}
