"use client";

import React from "react";
import { notFound, useParams } from "next/navigation";
import { StaticPageWrapper } from "@/components/StaticPageWrapper";
import { ShieldAlert, FileText, Cookie } from "lucide-react";

interface ContentBlock {
  title: string;
  subtitle: string;
  category: string;
  icon: React.ReactNode;
  body: React.ReactNode;
}

const legalContent: Record<string, ContentBlock> = {
  "privacy": {
    category: "Legal & Privacy",
    title: "Privacy Policy",
    subtitle: "How we collect, protect, and process your personal data when you use ResumeFlow.",
    icon: <ShieldAlert className="w-8 h-8 text-rose-600" />,
    body: (
      <div className="space-y-6 text-xs md:text-sm">
        <p className="text-slate-500 italic">Last updated: July 16, 2026</p>
        <p className="text-slate-600 leading-relaxed">
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        <p className="text-slate-600 leading-relaxed">
          We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </p>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Interpretation and Definitions</h2>
          <h3 className="text-sm font-semibold text-slate-700">Interpretation</h3>
          <p className="text-slate-600 leading-relaxed">The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
          <h3 className="text-sm font-semibold text-slate-700">Definitions</h3>
          <p className="text-slate-600 leading-relaxed">For the purposes of this Privacy Policy:</p>
          <ul className="list-disc pl-5 space-y-3 text-slate-600">
            <li><strong className="text-slate-800">Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong className="text-slate-800">Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong className="text-slate-800">Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Privacy Policy) refers to Resume Flow.</li>
            <li><strong className="text-slate-800">Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong className="text-slate-800">Country</strong> refers to: Telangana, India.</li>
            <li><strong className="text-slate-800">Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
            <li><strong className="text-slate-800">Personal Data</strong> (or &quot;Personal Information&quot;) is any information that relates to an identified or identifiable individual. We use &quot;Personal Data&quot; and &quot;Personal Information&quot; interchangeably unless a law uses a specific term.</li>
            <li><strong className="text-slate-800">Service</strong> refers to the Website.</li>
            <li><strong className="text-slate-800">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
            <li><strong className="text-slate-800">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            <li><strong className="text-slate-800">Website</strong> refers to Resume Flow, accessible from <a href="https://resumeflow.harshithkumar.in" target="_blank" rel="noopener noreferrer" className="text-rose-600 hover:underline font-medium">https://resumeflow.harshithkumar.in</a>.</li>
            <li><strong className="text-slate-800">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Collecting and Using Your Personal Data</h2>
          <h3 className="text-sm font-semibold text-slate-700">Types of Data Collected</h3>
          <h4 className="text-xs font-bold text-slate-700 uppercase tracking-wider">Personal Data</h4>
          <p className="text-slate-600 leading-relaxed">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
          <ul className="list-disc pl-5 space-y-1 text-slate-600">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
          </ul>

          <h4 className="text-xs font-bold text-slate-700 uppercase tracking-wider mt-4">Usage Data</h4>
          <p className="text-slate-600 leading-relaxed">Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
          <p className="text-slate-600 leading-relaxed">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device&apos;s unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
          <p className="text-slate-600 leading-relaxed">We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.</p>

          <h4 className="text-xs font-bold text-slate-700 uppercase tracking-wider mt-4">Tracking Technologies and Cookies</h4>
          <p className="text-slate-600 leading-relaxed">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
          <ul className="list-disc pl-5 space-y-2 text-slate-600">
            <li><strong className="text-slate-800">Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
            <li><strong className="text-slate-800">Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.</li>
          </ul>
          <p className="text-slate-600 leading-relaxed">Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
          <p className="text-slate-600 leading-relaxed">Where required by law, we use non-essential cookies (such as analytics, advertising, and remarketing cookies) only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool (if available) or through Your browser/device settings. Withdrawing consent does not affect the lawfulness of processing based on consent before its withdrawal.</p>
          <p className="text-slate-600 leading-relaxed font-semibold">We use both Session and Persistent Cookies for the purposes set out below:</p>
          <ul className="list-disc pl-5 space-y-3 text-slate-600">
            <li>
              <strong className="text-slate-800">Necessary / Essential Cookies</strong><br />
              Type: Session Cookies<br />
              Administered by: Us<br />
              Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
            </li>
            <li>
              <strong className="text-slate-800">Cookies Policy / Notice Acceptance Cookies</strong><br />
              Type: Persistent Cookies<br />
              Administered by: Us<br />
              Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
            </li>
            <li>
              <strong className="text-slate-800">Functionality Cookies</strong><br />
              Type: Persistent Cookies<br />
              Administered by: Us<br />
              Purpose: These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference.
            </li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Use of Your Personal Data</h2>
          <p className="text-slate-600 leading-relaxed">The Company may use Personal Data for the following purposes:</p>
          <ul className="list-disc pl-5 space-y-2 text-slate-600">
            <li><strong className="text-slate-800">To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
            <li><strong className="text-slate-800">To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
            <li><strong className="text-slate-800">For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
            <li><strong className="text-slate-800">To contact You:</strong> By email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
            <li><strong className="text-slate-800">To provide You</strong> with news, special offers, and general information about other goods, services and events which We offer.</li>
            <li><strong className="text-slate-800">To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
            <li><strong className="text-slate-800">For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of assets.</li>
            <li><strong className="text-slate-800">For other purposes</strong>: Such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service.</li>
          </ul>
          <p className="text-slate-600 leading-relaxed font-semibold mt-3">We may share Your Personal Data in the following situations:</p>
          <ul className="list-disc pl-5 space-y-2 text-slate-600">
            <li><strong className="text-slate-800">With Service Providers:</strong> To monitor and analyze the use of our Service, to contact You.</li>
            <li><strong className="text-slate-800">For business transfers:</strong> In connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition.</li>
            <li><strong className="text-slate-800">With Affiliates:</strong> We will require those affiliates to honor this Privacy Policy.</li>
            <li><strong className="text-slate-800">With business partners:</strong> To offer You certain products, services or promotions.</li>
            <li><strong className="text-slate-800">With other users:</strong> If Our Service offers public areas, when You share Personal Data or otherwise interact in the public areas.</li>
            <li><strong className="text-slate-800">With Your consent</strong>: We may disclose Your Personal Data for any other purpose with Your consent.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Retention of Your Personal Data</h2>
          <p className="text-slate-600 leading-relaxed">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>
          <p className="text-slate-600 leading-relaxed">Where possible, We apply shorter retention periods and/or reduce identifiability by deleting, aggregating, or anonymizing data. We apply different retention periods to different categories of Personal Data based on the purpose of processing and legal obligations:</p>
          <ul className="list-disc pl-5 space-y-3 text-slate-600">
            <li>
              <strong className="text-slate-800">Account Information</strong>
              <ul className="list-disc pl-5 mt-1 space-y-1">
                <li>User Accounts: retained for the duration of your account relationship plus up to 24 months after account closure.</li>
              </ul>
            </li>
            <li>
              <strong className="text-slate-800">Customer Support Data</strong>
              <ul className="list-disc pl-5 mt-1 space-y-1">
                <li>Support tickets and correspondence: up to 24 months from the date of ticket closure.</li>
                <li>Chat transcripts: up to 24 months for quality assurance and staff training purposes.</li>
              </ul>
            </li>
            <li>
              <strong className="text-slate-800">Usage Data</strong>
              <ul className="list-disc pl-5 mt-1 space-y-1">
                <li>Website analytics data (cookies, IP addresses, device identifiers): up to 24 months from the date of collection.</li>
                <li>Server logs (IP addresses, access times): up to 24 months for security monitoring and troubleshooting purposes.</li>
              </ul>
            </li>
          </ul>
          <p className="text-slate-600 leading-relaxed">Usage Data is retained in accordance with the retention periods described above, and may be retained longer only where necessary for security, fraud prevention, or legal compliance.</p>
          <p className="text-slate-600 leading-relaxed">We may retain Personal Data beyond the periods stated above for different reasons: legal obligation, legal claims, your explicit request, or technical limitations (data exists in backup systems).</p>
          <p className="text-slate-600 leading-relaxed">When retention periods expire, We securely delete or anonymize Personal Data according to the following procedures: deletion from active systems, residual copies may remain in encrypted backups for a limited period, and in some cases We convert Personal Data into anonymous statistical data that may be retained indefinitely for research and analytics.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Transfer of Your Personal Data</h2>
          <p className="text-slate-600 leading-relaxed">Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. This information may be transferred to and maintained on computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ.</p>
          <p className="text-slate-600 leading-relaxed">Where required by applicable law, We will ensure that international transfers of Your Personal Data are subject to appropriate safeguards. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Delete Your Personal Data</h2>
          <p className="text-slate-600 leading-relaxed">You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Our Service may give You the ability to delete certain information about You from within the Service.</p>
          <p className="text-slate-600 leading-relaxed">You may update, amend, or delete Your information at any time by signing in to Your Account and visiting the account settings section. You may also contact Us to request access to, correct, or delete any Personal Data that You have provided to Us.</p>
          <p className="text-slate-600 leading-relaxed">Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Disclosure of Your Personal Data</h2>
          <h3 className="text-sm font-semibold text-slate-700">Business Transactions</h3>
          <p className="text-slate-600 leading-relaxed">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
          <h3 className="text-sm font-semibold text-slate-700">Law enforcement</h3>
          <p className="text-slate-600 leading-relaxed">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>
          <h3 className="text-sm font-semibold text-slate-700">Other legal requirements</h3>
          <p className="text-slate-600 leading-relaxed">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to comply with a legal obligation, protect and defend the rights or property of the Company, prevent or investigate possible wrongdoing, protect the personal safety of Users, or protect against legal liability.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Security of Your Personal Data</h2>
          <p className="text-slate-600 leading-relaxed">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Children&apos;s Privacy</h2>
          <p className="text-slate-600 leading-relaxed">Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If We become aware that We have collected Personal Data from anyone under the age of 16 without verification of parental consent, We take steps to remove that information from Our servers.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Links to Other Websites</h2>
          <p className="text-slate-600 leading-relaxed">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&apos;s site. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Changes to this Privacy Policy</h2>
          <p className="text-slate-600 leading-relaxed">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Contact Us</h2>
          <p className="text-slate-600 leading-relaxed">If you have any questions about this Privacy Policy, You can contact us by visiting our website: <a href="https://resumeflow.harshithkumar.in" target="_blank" rel="noopener noreferrer" className="text-rose-600 hover:underline font-medium">https://resumeflow.harshithkumar.in</a>.</p>
        </section>
      </div>
    ),
  },
  "terms": {
    category: "Legal Agreements",
    title: "Terms of Service",
    subtitle: "The rules and guidelines governing your use of the ResumeFlow platform.",
    icon: <FileText className="w-8 h-8 text-rose-600" />,
    body: (
      <div className="space-y-6 text-xs md:text-sm">
        <p className="text-slate-500 italic">Last updated: July 16, 2026</p>
        <p className="text-slate-600 leading-relaxed font-medium">Please read these terms and conditions carefully before using Our Service.</p>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Interpretation and Definitions</h2>
          <h3 className="text-sm font-semibold text-slate-700">Interpretation</h3>
          <p className="text-slate-600 leading-relaxed">The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
          <h3 className="text-sm font-semibold text-slate-700">Definitions</h3>
          <p className="text-slate-600 leading-relaxed">For the purposes of these Terms and Conditions:</p>
          <ul className="list-disc pl-5 space-y-3 text-slate-600">
            <li><strong className="text-slate-800">Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party.</li>
            <li><strong className="text-slate-800">Country</strong> refers to: Telangana, India.</li>
            <li><strong className="text-slate-800">Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot;) refers to Resume Flow.</li>
            <li><strong className="text-slate-800">Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
            <li><strong className="text-slate-800">Service</strong> refers to the Website.</li>
            <li><strong className="text-slate-800">Terms and Conditions</strong> (also referred to as &quot;Terms&quot;) means these Terms and Conditions, including any documents expressly incorporated by reference.</li>
            <li><strong className="text-slate-800">Third-Party Social Media Service</strong> means any services or content provided by a third party that is displayed, included, made available, or linked to through the Service.</li>
            <li><strong className="text-slate-800">Website</strong> refers to Resume Flow, accessible from <a href="https://resumeflow.harshithkumar.in" target="_blank" rel="noopener noreferrer" className="text-rose-600 hover:underline font-medium">https://resumeflow.harshithkumar.in</a>.</li>
            <li><strong className="text-slate-800">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Acknowledgment</h2>
          <p className="text-slate-600 leading-relaxed">These are the Terms and Conditions governing the use of this Service and the agreement between You and the Company. Your access to and use of the Service is conditioned on Your acceptance of and compliance with these Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or use the Service.</p>
          <p className="text-slate-600 leading-relaxed">By accessing or using the Service You agree to be bound by these Terms and Conditions. If You disagree with any part of these Terms and Conditions then You may not access the Service. You represent that you are over the age of 18. The Company does not permit those under 18 to use the Service.</p>
          <p className="text-slate-600 leading-relaxed">Your access to and use of the Service is also subject to Our Privacy Policy, which describes how We collect, use, and disclose personal information.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Links to Other Websites</h2>
          <p className="text-slate-600 leading-relaxed">Our Service may contain links to third-party websites or services that are not owned or controlled by the Company. The Company has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third-party websites or services.</p>
          <p className="text-slate-600 leading-relaxed">The Service may also display, include, make available, or link to content or services provided by a Third-Party Social Media Service. A Third-Party Social Media Service is not owned or controlled by the Company, and the Company does not endorse or assume responsibility for any Third-Party Social Media Service.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Termination</h2>
          <p className="text-slate-600 leading-relaxed">We may terminate or suspend Your access immediately, without prior notice or liability, for any reason whatsoever, including without limitation if You breach these Terms and Conditions. Upon termination, Your right to use the Service will cease immediately.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Limitation of Liability</h2>
          <p className="text-slate-600 leading-relaxed">Notwithstanding any damages that You might incur, the entire liability of the Company and any of its suppliers under any provision of these Terms and Your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by You through the Service or 100 USD if You haven&apos;t purchased anything through the Service.</p>
          <p className="text-slate-600 leading-relaxed">To the maximum extent permitted by applicable law, in no event shall the Company or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, loss of data, business interruption, personal injury, loss of privacy), even if the Company or any supplier has been advised of the possibility of such damages.</p>
          <p className="text-slate-600 leading-relaxed">Some states do not allow the exclusion of implied warranties or limitation of liability for incidental or consequential damages, which means that some of the above limitations may not apply. In these states, each party&apos;s liability will be limited to the greatest extent permitted by law.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">&quot;AS IS&quot; and &quot;AS AVAILABLE&quot; Disclaimer</h2>
          <p className="text-slate-600 leading-relaxed">The Service is provided to You &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, the Company, on its own behalf and on behalf of its Affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the Service.</p>
          <p className="text-slate-600 leading-relaxed">Without limiting the foregoing, neither the Company nor any of the company&apos;s provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the Service; (ii) that the Service will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content; or (iv) that the Service, its servers, or e-mails sent from the Company are free of viruses or other harmful components.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Governing Law</h2>
          <p className="text-slate-600 leading-relaxed">The laws of the Country, excluding its conflicts of law rules, shall govern these Terms and Your use of the Service. Your use of the Application may also be subject to other local, state, national, or international laws.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Disputes Resolution</h2>
          <p className="text-slate-600 leading-relaxed">If You have any concern or dispute about the Service, You agree to first try to resolve the dispute informally by contacting the Company.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">For European Union (EU) Users</h2>
          <p className="text-slate-600 leading-relaxed">If You are a European Union consumer, you will benefit from any mandatory provisions of the law of the country in which You are resident.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">United States Legal Compliance</h2>
          <p className="text-slate-600 leading-relaxed">You represent and warrant that (i) You are not located in a country that is subject to the United States government embargo, or that has been designated as a &quot;terrorist supporting&quot; country, and (ii) You are not listed on any United States government list of prohibited or restricted parties.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Severability and Waiver</h2>
          <h3 className="text-sm font-semibold text-slate-700">Severability</h3>
          <p className="text-slate-600 leading-relaxed">If any provision of these Terms is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.</p>
          <h3 className="text-sm font-semibold text-slate-700">Waiver</h3>
          <p className="text-slate-600 leading-relaxed">Except as provided herein, the failure to exercise a right or to require performance of an obligation under these Terms shall not affect a party&apos;s ability to exercise such right or require such performance at any time thereafter.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Translation Interpretation</h2>
          <p className="text-slate-600 leading-relaxed">These Terms and Conditions may have been translated if We have made them available to You on our Service. You agree that the original English text shall prevail in the case of a dispute.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Changes to These Terms and Conditions</h2>
          <p className="text-slate-600 leading-relaxed">We reserve the right, at Our sole discretion, to modify or replace these Terms at any time. If a revision is material We will make reasonable efforts to provide at least 30 days&apos; notice prior to any new terms taking effect. By continuing to access or use Our Service after those revisions become effective, You agree to be bound by the revised terms.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-slate-800">Contact Us</h2>
          <p className="text-slate-600 leading-relaxed">If you have any questions about these Terms and Conditions, You can contact us by visiting our website: <a href="https://resumeflow.harshithkumar.in" target="_blank" rel="noopener noreferrer" className="text-rose-600 hover:underline font-medium">https://resumeflow.harshithkumar.in</a>.</p>
        </section>
      </div>
    ),
  },
  "cookies": {
    category: "Legal & Settings",
    title: "Cookie Policy & Settings",
    subtitle: "Manage how local storage and session markers are utilized to enhance your workspace.",
    icon: <Cookie className="w-8 h-8 text-rose-600" />,
    body: (
      <div className="space-y-8 text-xs md:text-sm">
        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-800">1. What are cookies and local storage?</h2>
          <p className="text-slate-600 leading-relaxed">
            We use local session cookies to securely verify your authentication status during database queries.
            Additionally, browser local storage is utilized to temporarily store user interface layout states (such as maximizing your workspace canvas) and cache preview data.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-800">2. Essential Cookies</h2>
          <p className="text-slate-600 leading-relaxed">
            These cookies are strictly necessary to provide you with secure dashboard access, database sync, and placement tools.
            Disabling essential cookies will block you from signing in or tailoring resumes.
          </p>
        </section>
      </div>
    ),
  },
};

export default function LegalSlugPage() {
  const { slug } = useParams();
  const pageData = legalContent[slug as string];

  if (!pageData) {
    notFound();
  }

  return (
    <StaticPageWrapper
      category={pageData.category}
      title={pageData.title}
      subtitle={pageData.subtitle}
    >
      <div className="flex gap-4 items-center mb-6">
        {pageData.icon}
        <div className="h-px bg-slate-200/60 flex-1" />
      </div>
      {pageData.body}
    </StaticPageWrapper>
  );
}
